package Jframe;

import Adapters.dbhandler;
import java.awt.Color;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author HIMANSHU TYAGI BCA SEM 5 ROLL NO 200954106032.
 */
public class ControlPanel extends javax.swing.JFrame {

    private final Color HOVER_SHADOW = new Color(143, 92, 26);
    private final Color HOVER_SHADOW_EXIT = new Color(242, 242, 242);

    private int rowsInDB = 0;
    private ResultSet rst;
    private static Connection conn;
    private PreparedStatement pst;
    private String sql, Username, isLoggedIn;

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        try {
            conn = dbhandler.getDbConnection();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        initComponents();
        layoutSetUp();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("resources/SCZ.png")));
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-YYYY");
        dateLabel.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timeLabel.setText(s.format(d));
            }
        }).start();
    }

    private void layoutSetUp() {

        showTime();
        showDate();
        try {

            // getting total  No of books from db
            sql = "SELECT COUNT(1) as NumOfRows  FROM `books`;";
            pst = conn.prepareStatement(sql);
            rst = pst.executeQuery();
            rst.next();
            rowsInDB = rst.getInt("NumOfRows");
            noOfBooksLabel.setText(Integer.toString(rowsInDB));

            // getting total No of students from db
            sql = "SELECT COUNT(1) as NumOfRows  FROM `students`;";
            pst = conn.prepareStatement(sql);
            rst = pst.executeQuery();
            rst.next();
            rowsInDB = rst.getInt("NumOfRows");
            noOfStudentsLabel.setText(Integer.toString(rowsInDB));

            // getting logged in user form db
            sql = "SELECT `userLoggedIn` FROM `masterdata`;";
            pst = conn.prepareStatement(sql);
            rst = pst.executeQuery();
            rst.next();
            Username = rst.getString("userLoggedIn");
            welcomeNoteUsername.setText("Welcome ! " + Username);

            // GETTING TOTAL NUMBER OF BOOKS ISSUED TILL NOW.
            sql = "SELECT COUNT(1) as NumOfRows  FROM `issuedBooks`;";
            pst = conn.prepareStatement(sql);
            rst = pst.executeQuery();
            rst.next();
            rowsInDB = rst.getInt("NumOfRows");
            noOfIssuedBooksLabel.setText(Integer.toString(rowsInDB));

            // GETTING TOTAL NUMBER OF DEFAULTERS.
//            sql = "Select  COUNT(1) as NumOfRows from `issuedBooks` where `defaultDate` < 'GETDATE()' ;";
            java.sql.Date date = new java.sql.Date(System.currentTimeMillis());
            sql = "Select  COUNT(1) as NumOfRows from `issuedBooks` where `defaultDate` < '" + date + "' ;";

            pst = conn.prepareStatement(sql);
            rst = pst.executeQuery();
            if (rst.next()) {
                rowsInDB = rst.getInt("NumOfRows");
//                System.out.println("DEFAULTERS FOUND IN DB = " + Integer.toString(rowsInDB));
            }
            noOfDefaultersLabel.setText(Integer.toString(rowsInDB));

        } catch (SQLException e) {

            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftNavPanel = new javax.swing.JPanel();
        homepagelpi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        featureLPL = new javax.swing.JLabel();
        manageStudentlpi = new javax.swing.JPanel();
        manageStudentsLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        logoutLpi = new javax.swing.JPanel();
        exitLabelBtn = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        manageBookslpi = new javax.swing.JPanel();
        manageBooksLabel = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        issueBooksLPI = new javax.swing.JPanel();
        issueBooksLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        returnBooksLPI = new javax.swing.JPanel();
        returnBookLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        viewRecordLpi = new javax.swing.JPanel();
        viewRecordLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        viewIssuedBooksLpi = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        defaulterLpi = new javax.swing.JPanel();
        defaulterLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        topNavBar = new javax.swing.JPanel();
        MenuBtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        libararyManagementSystemNote = new javax.swing.JLabel();
        welcomeNoteUsername = new javax.swing.JLabel();
        dateAndTimeLabel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        noOfStudentsLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        noOfIssuedBooksLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        noOfDefaultersLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        backUpDataLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        noOfBooksLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        searchBookLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        searchStudentLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        viewBookIssuedTodayLabel2 = new javax.swing.JLabel();
        midImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control Panel");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftNavPanel.setBackground(new java.awt.Color(51, 51, 51));
        leftNavPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homepagelpi.setBackground(new java.awt.Color(153, 51, 255));
        homepagelpi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(homepagelpi);
        jLabel1.setText("HomePage");
        homepagelpi.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel2.setLabelFor(homepagelpi);
        homepagelpi.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 40));

        leftNavPanel.add(homepagelpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 340, 60));

        featureLPL.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        featureLPL.setForeground(new java.awt.Color(255, 255, 255));
        featureLPL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        featureLPL.setText("Features");
        leftNavPanel.add(featureLPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 20));

        manageStudentlpi.setBackground(new java.awt.Color(80, 80, 80));
        manageStudentlpi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageStudentlpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageStudentlpiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageStudentlpiMouseExited(evt);
            }
        });
        manageStudentlpi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageStudentsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageStudentsLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageStudentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageStudentsLabel.setLabelFor(manageStudentlpi);
        manageStudentsLabel.setText("Manage Students");
        manageStudentsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageStudentsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageStudentsLabelMouseClicked(evt);
            }
        });
        manageStudentlpi.add(manageStudentsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        jLabel5.setLabelFor(manageStudentlpi);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageStudentlpi.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        jPanel19.setBackground(new java.awt.Color(80, 80, 80));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Manage Students");
        jPanel19.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        jPanel19.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        jPanel20.setBackground(new java.awt.Color(80, 80, 80));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("HomePage");
        jPanel20.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jPanel20.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 40));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        jPanel21.setBackground(new java.awt.Color(80, 80, 80));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("HomePage");
        jPanel21.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jPanel21.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 40));

        jPanel22.setBackground(new java.awt.Color(80, 80, 80));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("HomePage");
        jPanel22.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jPanel22.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 40));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        manageStudentlpi.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 340, 60));

        leftNavPanel.add(manageStudentlpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        logoutLpi.setBackground(new java.awt.Color(153, 51, 255));
        logoutLpi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLpiMouseClicked(evt);
            }
        });
        logoutLpi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitLabelBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitLabelBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitLabelBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exitLabelBtn.setLabelFor(logoutLpi);
        exitLabelBtn.setText("LogOut");
        exitLabelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelBtnMouseClicked(evt);
            }
        });
        logoutLpi.add(exitLabelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 120, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        jLabel13.setLabelFor(logoutLpi);
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLpi.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        leftNavPanel.add(logoutLpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 340, 60));

        manageBookslpi.setBackground(new java.awt.Color(80, 80, 80));
        manageBookslpi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageBookslpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageBookslpiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageBookslpiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageBookslpiMouseExited(evt);
            }
        });
        manageBookslpi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageBooksLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageBooksLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageBooksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageBooksLabel.setLabelFor(manageBookslpi);
        manageBooksLabel.setText("Manage Books");
        manageBooksLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageBooksLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageBooksLabelMouseClicked(evt);
            }
        });
        manageBookslpi.add(manageBooksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 130, -1));

        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel61.setLabelFor(manageBookslpi);
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageBookslpi.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 40, 40));

        leftNavPanel.add(manageBookslpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 60));

        issueBooksLPI.setBackground(new java.awt.Color(80, 80, 80));
        issueBooksLPI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        issueBooksLPI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issueBooksLPIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issueBooksLPIMouseExited(evt);
            }
        });
        issueBooksLPI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issueBooksLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        issueBooksLabel.setForeground(new java.awt.Color(255, 255, 255));
        issueBooksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        issueBooksLabel.setLabelFor(issueBooksLPI);
        issueBooksLabel.setText("Issue Book");
        issueBooksLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        issueBooksLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueBooksLabelMouseClicked(evt);
            }
        });
        issueBooksLPI.add(issueBooksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        jLabel15.setLabelFor(issueBooksLPI);
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        issueBooksLPI.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 40));

        leftNavPanel.add(issueBooksLPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 340, 60));

        returnBooksLPI.setBackground(new java.awt.Color(80, 80, 80));
        returnBooksLPI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBooksLPI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBooksLPIMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnBooksLPIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnBooksLPIMouseExited(evt);
            }
        });
        returnBooksLPI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnBookLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        returnBookLabel.setForeground(new java.awt.Color(255, 255, 255));
        returnBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnBookLabel.setLabelFor(returnBooksLPI);
        returnBookLabel.setText("Return Books");
        returnBookLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBookLabelMouseClicked(evt);
            }
        });
        returnBooksLPI.add(returnBookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 130, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        jLabel17.setLabelFor(returnBooksLPI);
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBooksLPI.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 40));

        leftNavPanel.add(returnBooksLPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 340, 60));

        viewRecordLpi.setBackground(new java.awt.Color(80, 80, 80));
        viewRecordLpi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewRecordLpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewRecordLpiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewRecordLpiMouseExited(evt);
            }
        });
        viewRecordLpi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewRecordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewRecordLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewRecordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewRecordLabel.setLabelFor(viewRecordLpi);
        viewRecordLabel.setText("View Records");
        viewRecordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewRecordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRecordLabelMouseClicked(evt);
            }
        });
        viewRecordLpi.add(viewRecordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 130, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        jLabel19.setLabelFor(viewRecordLpi);
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewRecordLpi.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 40));

        leftNavPanel.add(viewRecordLpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 340, 60));

        viewIssuedBooksLpi.setBackground(new java.awt.Color(80, 80, 80));
        viewIssuedBooksLpi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewIssuedBooksLpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewIssuedBooksLpiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewIssuedBooksLpiMouseExited(evt);
            }
        });
        viewIssuedBooksLpi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(255, 255, 255));
        searchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchLabel.setLabelFor(viewIssuedBooksLpi);
        searchLabel.setText("Advance Search ");
        searchLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLabelMouseClicked(evt);
            }
        });
        viewIssuedBooksLpi.add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 180, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Books_26px.png"))); // NOI18N
        jLabel21.setLabelFor(viewIssuedBooksLpi);
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewIssuedBooksLpi.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 40));

        leftNavPanel.add(viewIssuedBooksLpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 340, 60));

        defaulterLpi.setBackground(new java.awt.Color(80, 80, 80));
        defaulterLpi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        defaulterLpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defaulterLpiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                defaulterLpiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                defaulterLpiMouseExited(evt);
            }
        });
        defaulterLpi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        defaulterLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        defaulterLabel.setForeground(new java.awt.Color(255, 255, 255));
        defaulterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defaulterLabel.setLabelFor(defaulterLpi);
        defaulterLabel.setText("Defaulters ");
        defaulterLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        defaulterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defaulterLabelMouseClicked(evt);
            }
        });
        defaulterLpi.add(defaulterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 150, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        jLabel23.setLabelFor(defaulterLpi);
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        defaulterLpi.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        leftNavPanel.add(defaulterLpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 340, 60));

        getContentPane().add(leftNavPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 670));

        topNavBar.setBackground(new java.awt.Color(153, 51, 255));
        topNavBar.setPreferredSize(new java.awt.Dimension(1300, 70));
        topNavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        MenuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBtnMouseClicked(evt);
            }
        });
        topNavBar.add(MenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 50, 40));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        topNavBar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 5, 5, -1));

        libararyManagementSystemNote.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        libararyManagementSystemNote.setForeground(new java.awt.Color(255, 255, 255));
        libararyManagementSystemNote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libararyManagementSystemNote.setText("Library Management System");
        libararyManagementSystemNote.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        topNavBar.add(libararyManagementSystemNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 430, 40));

        welcomeNoteUsername.setFont(new java.awt.Font("Segoe UI", 2, 30)); // NOI18N
        welcomeNoteUsername.setForeground(new java.awt.Color(255, 255, 255));
        welcomeNoteUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        welcomeNoteUsername.setText("Welcome ! Admin");
        topNavBar.add(welcomeNoteUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 310, 40));

        dateAndTimeLabel.setBackground(new java.awt.Color(153, 51, 255));
        dateAndTimeLabel.setForeground(new java.awt.Color(255, 255, 255));

        dateLabel.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("date");

        timeLabel.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("time");

        javax.swing.GroupLayout dateAndTimeLabelLayout = new javax.swing.GroupLayout(dateAndTimeLabel);
        dateAndTimeLabel.setLayout(dateAndTimeLabelLayout);
        dateAndTimeLabelLayout.setHorizontalGroup(
            dateAndTimeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dateAndTimeLabelLayout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(dateAndTimeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dateAndTimeLabelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(257, Short.MAX_VALUE)))
        );
        dateAndTimeLabelLayout.setVerticalGroup(
            dateAndTimeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateAndTimeLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dateAndTimeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dateAndTimeLabelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        topNavBar.add(dateAndTimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 520, 50));

        getContentPane().add(topNavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 50));

        rightPanel.setBackground(new java.awt.Color(51, 51, 51));
        rightPanel.setForeground(new java.awt.Color(255, 255, 255));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. of Books");
        rightPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No. of Students");
        rightPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 160, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        noOfStudentsLabel.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        noOfStudentsLabel.setForeground(new java.awt.Color(102, 102, 102));
        noOfStudentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfStudentsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        noOfStudentsLabel.setText("2500");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(noOfStudentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(noOfStudentsLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        rightPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 230, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(153, 51, 255)));
        jPanel4.setPreferredSize(new java.awt.Dimension(230, 140));

        noOfIssuedBooksLabel.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        noOfIssuedBooksLabel.setForeground(new java.awt.Color(102, 102, 102));
        noOfIssuedBooksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfIssuedBooksLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        noOfIssuedBooksLabel.setText("7095");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(noOfIssuedBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(noOfIssuedBooksLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        rightPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 230, 140));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Issued Books");
        rightPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 160, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Defaulter's");
        rightPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 160, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));

        noOfDefaultersLabel.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        noOfDefaultersLabel.setForeground(new java.awt.Color(102, 102, 102));
        noOfDefaultersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfDefaultersLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        noOfDefaultersLabel.setText("304");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(noOfDefaultersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(noOfDefaultersLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        rightPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 80, 230, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(255, 51, 51)));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.setPreferredSize(new java.awt.Dimension(230, 80));

        backUpDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backUpDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backUpDataLabel.setText("BackUp Data");
        backUpDataLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backUpDataLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(backUpDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backUpDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rightPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 560, 230, 80));

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(153, 255, 153)));
        jPanel7.setPreferredSize(new java.awt.Dimension(230, 140));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        noOfBooksLabel.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        noOfBooksLabel.setForeground(new java.awt.Color(102, 102, 102));
        noOfBooksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOfBooksLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        noOfBooksLabel.setText("10500");
        noOfBooksLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noOfBooksLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(noOfBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(noOfBooksLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 140));

        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(153, 51, 255)));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.setPreferredSize(new java.awt.Dimension(230, 80));

        searchBookLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchBookLabel.setText("Search Book ");
        searchBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBookLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(searchBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(153, 153, 153)));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.setPreferredSize(new java.awt.Dimension(230, 80));

        searchStudentLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchStudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchStudentLabel.setText("Students Enrolled");
        searchStudentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchStudentLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(searchStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 230, 80));

        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(153, 255, 153)));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        viewBookIssuedTodayLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewBookIssuedTodayLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewBookIssuedTodayLabel2.setText("Books Registered");
        viewBookIssuedTodayLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewBookIssuedTodayLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBookIssuedTodayLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(viewBookIssuedTodayLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewBookIssuedTodayLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        midImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/midImage.jpeg"))); // NOI18N
        rightPanel.add(midImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 236, 980, 300));

        getContentPane().add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 1030, 670));

        setSize(new java.awt.Dimension(1382, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelBtnMouseClicked

        try {

            sql = "update `masterdata` set `userLoggedIn` = 'None' , `isLoggedIn` = 'false';";
            pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            LoginPage next = new LoginPage();
            next.setVisible(true);
            dispose();

        } catch (SQLException ex) {
            Logger.getLogger(ControlPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exitLabelBtnMouseClicked

    private void logoutLpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLpiMouseClicked

        try {
            isLoggedIn = "false";
            Username = "none";
            sql = "update `masterdata` set `userLoggedIn` = 'None' , `isLoggedIn` = 'false';";
            pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            LoginPage next = new LoginPage();
            next.setVisible(true);
            dispose();

        } catch (SQLException ex) {
            Logger.getLogger(ControlPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoutLpiMouseClicked

    private void manageStudentsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentsLabelMouseClicked
        // GOING TO MANAGE STUDENTS FRAME AS MANAGESTUDENTS.JAVA

        ManageStudents next = new ManageStudents();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_manageStudentsLabelMouseClicked

    private void issueBooksLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBooksLabelMouseClicked

        IssueBooks next = new IssueBooks();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_issueBooksLabelMouseClicked

    private void returnBookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookLabelMouseClicked

        ReturnBooks next = new ReturnBooks();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnBookLabelMouseClicked

    private void returnBooksLPIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBooksLPIMouseClicked

        ReturnBooks next = new ReturnBooks();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnBooksLPIMouseClicked

    private void searchStudentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStudentLabelMouseClicked

        new SearchStudent().setVisible(true);
        dispose();

    }//GEN-LAST:event_searchStudentLabelMouseClicked

    private void defaulterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterLabelMouseClicked

        Defaulters next = new Defaulters();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_defaulterLabelMouseClicked

    private void defaulterLpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterLpiMouseClicked

        Defaulters next = new Defaulters();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_defaulterLpiMouseClicked

    private void viewRecordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRecordLabelMouseClicked

        new viewRecords().setVisible(true);
        dispose();
    }//GEN-LAST:event_viewRecordLabelMouseClicked

    private void searchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseClicked

        new SearchIssuedBooksPanel().setVisible(true);
        dispose();
    }//GEN-LAST:event_searchLabelMouseClicked

    private void manageBookslpiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBookslpiMouseEntered

        manageBookslpi.setBackground(Color.BLACK);
    }//GEN-LAST:event_manageBookslpiMouseEntered

    private void manageBookslpiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBookslpiMouseExited

        manageBookslpi.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_manageBookslpiMouseExited

    private void manageStudentlpiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentlpiMouseEntered

        manageStudentlpi.setBackground(Color.BLACK);
    }//GEN-LAST:event_manageStudentlpiMouseEntered

    private void manageStudentlpiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentlpiMouseExited

        manageStudentlpi.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_manageStudentlpiMouseExited

    private void issueBooksLPIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBooksLPIMouseEntered

        issueBooksLPI.setBackground(Color.BLACK);
    }//GEN-LAST:event_issueBooksLPIMouseEntered

    private void issueBooksLPIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBooksLPIMouseExited

        issueBooksLPI.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_issueBooksLPIMouseExited

    private void returnBooksLPIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBooksLPIMouseEntered
        returnBooksLPI.setBackground(Color.BLACK);
    }//GEN-LAST:event_returnBooksLPIMouseEntered

    private void returnBooksLPIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBooksLPIMouseExited

        returnBooksLPI.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_returnBooksLPIMouseExited

    private void viewRecordLpiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRecordLpiMouseEntered

        viewRecordLpi.setBackground(Color.BLACK);
    }//GEN-LAST:event_viewRecordLpiMouseEntered

    private void viewRecordLpiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRecordLpiMouseExited

        viewRecordLpi.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_viewRecordLpiMouseExited

    private void viewIssuedBooksLpiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewIssuedBooksLpiMouseEntered

        viewIssuedBooksLpi.setBackground(Color.BLACK);
    }//GEN-LAST:event_viewIssuedBooksLpiMouseEntered

    private void viewIssuedBooksLpiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewIssuedBooksLpiMouseExited

        viewIssuedBooksLpi.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_viewIssuedBooksLpiMouseExited

    private void defaulterLpiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterLpiMouseEntered

        defaulterLpi.setBackground(Color.BLACK);
    }//GEN-LAST:event_defaulterLpiMouseEntered

    private void defaulterLpiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterLpiMouseExited

        defaulterLpi.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_defaulterLpiMouseExited

    private void noOfBooksLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noOfBooksLabelMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_noOfBooksLabelMouseEntered

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
//        jPanel7.setBounds(ren);

    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
//        jPanel7.setBounds(rex);

    }//GEN-LAST:event_jPanel7MouseExited

    private void manageBookslpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBookslpiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manageBookslpiMouseClicked

    private void manageBooksLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBooksLabelMouseClicked

        new ManageBooks().setVisible(true);
        dispose();
    }//GEN-LAST:event_manageBooksLabelMouseClicked

    private void viewBookIssuedTodayLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBookIssuedTodayLabel2MouseClicked

        new SearchInAllBook().setVisible(true);
        dispose();
    }//GEN-LAST:event_viewBookIssuedTodayLabel2MouseClicked

    private void searchBookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBookLabelMouseClicked

        new SearchInAllBook().setVisible(true);
        dispose();
    }//GEN-LAST:event_searchBookLabelMouseClicked

    private void backUpDataLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backUpDataLabelMouseClicked

        String path = null;
        Process p = null;
        String filename = "";

        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);  //jLabel6
        String date = new SimpleDateFormat("YYYY-MM-DD").format(new Date());

        try {

            File f = fc.getSelectedFile();
            path = f.getAbsolutePath();
            path = path.replace('\\', '/');
            path = path + "_" + date + ".sql";

            Runtime runtime = Runtime.getRuntime();
            p = runtime.exec("C://xampp//mysql//bin//mysqldump.exe -Uroot  --add-drop-database -B lms -R" + path);

            int processComplete = p.waitFor();
            if (processComplete == 0) {
                JOptionPane.showMessageDialog(this, " BackUp Created Successfully !", "BackUP Creation Result", HEIGHT);
            } else {
                JOptionPane.showMessageDialog(this, "Can't Create BackUp", "BackUP Creation Result", HEIGHT);
            }
        } catch (Exception e) {

            e.printStackTrace();
        }

    }//GEN-LAST:event_backUpDataLabelMouseClicked

    private void MenuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBtnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ControlPanel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuBtn;
    private javax.swing.JLabel backUpDataLabel;
    private javax.swing.JPanel dateAndTimeLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel defaulterLabel;
    private javax.swing.JPanel defaulterLpi;
    private javax.swing.JLabel exitLabelBtn;
    private javax.swing.JLabel featureLPL;
    private javax.swing.JPanel homepagelpi;
    private javax.swing.JPanel issueBooksLPI;
    private javax.swing.JLabel issueBooksLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel leftNavPanel;
    private javax.swing.JLabel libararyManagementSystemNote;
    private javax.swing.JPanel logoutLpi;
    private javax.swing.JLabel manageBooksLabel;
    private javax.swing.JPanel manageBookslpi;
    private javax.swing.JPanel manageStudentlpi;
    private javax.swing.JLabel manageStudentsLabel;
    private javax.swing.JLabel midImage;
    private javax.swing.JLabel noOfBooksLabel;
    private javax.swing.JLabel noOfDefaultersLabel;
    private javax.swing.JLabel noOfIssuedBooksLabel;
    private javax.swing.JLabel noOfStudentsLabel;
    private javax.swing.JLabel returnBookLabel;
    private javax.swing.JPanel returnBooksLPI;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel searchBookLabel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel searchStudentLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel topNavBar;
    private javax.swing.JLabel viewBookIssuedTodayLabel2;
    private javax.swing.JPanel viewIssuedBooksLpi;
    private javax.swing.JLabel viewRecordLabel;
    private javax.swing.JPanel viewRecordLpi;
    private javax.swing.JLabel welcomeNoteUsername;
    // End of variables declaration//GEN-END:variables
}
