package Jframe;

import Adapters.dbhandler;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author HIMANSHU TYAGI BCA SEM 5 ROLL NO 200954106032.
 */
public class IssueBooks extends javax.swing.JFrame {

    private ResultSet rst;
    private static Connection conn;
    private  PreparedStatement pst;
    private  String bookId, subject, studentId, studentStatus, isIssued,sql;
    private Date issueDate, returnDate, defaultDate;
    private int booksIssuedTillNow;
    private java.sql.Date sqlDate;

    /**
     * Creates new form IssueBooks
     */
    public IssueBooks() {
        try {
            conn = dbhandler.getDbConnection();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("resources/SCZ.png")));
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

    }

    private void getData() {

        bookId = bookIdEditText.getText();
        studentId = studentIdEditText.getText();
        issueDate = issueDateChooser.getDate();
        returnDate = returnDateChooser.getDate();
    }

    private void AddDaysToDate(Date dateToBeChanged, int daysToBeAdded) {
        //create instance of the Calendar class and set the date to the given date  
        Calendar cal = Calendar.getInstance();
        cal.setTime(dateToBeChanged);

        // use add() method to add the days to the given date  
        cal.add(Calendar.DAY_OF_MONTH, daysToBeAdded);
        defaultDate = cal.getTime();
    }

    private void getBookDetails() {

        bookId = bookIdEditText.getText();

        try {
           
            pst = conn.prepareStatement("Select * from `books` where bookId = '" + bookId + "';");
            rst = pst.executeQuery();
           if(rst.next()) {

                bookId = rst.getString("bookId");
                setBookIdLabel.setText(bookId);
                setBookNamelabel.setText(rst.getString("bookName"));
                setAuthorLabel.setText(rst.getString("authorName"));
                setIssuedToLabel.setText(rst.getString("issuedToStudId"));
                subject = rst.getString("subjectOfBook");
                setSubjectLabel.setText(subject);
            }else{
                BooksResultBox.setForeground(Color.WHITE);
                BooksResultBox.setText(" No such Book found in DataBase.");
                Timer timer = new Timer(3000, (ActionEvent arg0) -> {
                    BooksResultBox.setText(" ");
                });
                timer.setRepeats(false); // Only execute once
                timer.start();

                }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void getStudentDetails() {

        studentId = studentIdEditText.getText();

        try {
          
            pst = conn.prepareStatement("Select * from `students` where studentId = '" + studentId + "';");
            rst = pst.executeQuery();
            if(rst.next()) {

                studentId = rst.getString("studentId");
                setStudentIdLabel.setText(studentId);
                setStudentNamelabel.setText(rst.getString("studentName"));
                setCourseLabel.setText(rst.getString("course"));
                booksIssuedTillNow = rst.getInt("booksIssued");
                setIssuedBooksLabel.setText(Integer.toString(booksIssuedTillNow));
                setStudentStatusLabel.setText(rst.getString("studentStatus"));
            }else{
                    studentResultBox.setForeground(Color.red);
                    studentResultBox.setText(" No such student found in DataBase.");
                    Timer timer = new Timer(3000, (ActionEvent arg0) -> {
                    studentResultBox.setText(" ");
                    });
                    timer.setRepeats(false); // Only execute once
                    timer.start();
                    
                }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottomPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        booksDetailsLabel = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bookNamelabel = new javax.swing.JLabel();
        bookIdLabel = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        issuedToLabel = new javax.swing.JLabel();
        setBookIdLabel = new javax.swing.JLabel();
        setBookNamelabel = new javax.swing.JLabel();
        setAuthorLabel = new javax.swing.JLabel();
        setIssuedToLabel = new javax.swing.JLabel();
        setSubjectLabel = new javax.swing.JLabel();
        BooksResultBox = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        issueBookLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        issueStudentIdlabel = new javax.swing.JLabel();
        setDefaultDateLabel = new javax.swing.JLabel();
        issueDateLabel = new javax.swing.JLabel();
        resultBoxLabel = new javax.swing.JLabel();
        ReturnDateLabel = new javax.swing.JLabel();
        studentIdEditText = new app.bolivia.swing.JCTextField();
        bookIdEditText = new app.bolivia.swing.JCTextField();
        issueBookBtn = new javax.swing.JButton();
        issueBookIdLabel1 = new javax.swing.JLabel();
        issueDateChooser = new com.toedter.calendar.JDateChooser();
        returnDateChooser = new com.toedter.calendar.JDateChooser();
        centerPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        studentDetailsLabel = new javax.swing.JLabel();
        setIssuedBooksLabel = new javax.swing.JLabel();
        setCourseLabel = new javax.swing.JLabel();
        setStudentNamelabel = new javax.swing.JLabel();
        studentStatusLabel = new javax.swing.JLabel();
        setStudentStatusLabel = new javax.swing.JLabel();
        studentIdLabel = new javax.swing.JLabel();
        studentNamelabel = new javax.swing.JLabel();
        booksIssuedLabel = new javax.swing.JLabel();
        setStudentIdLabel = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();
        studentResultBox = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Issue Books");
        setMinimumSize(new java.awt.Dimension(1366, 770));
        setPreferredSize(new java.awt.Dimension(1366, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(255, 51, 51));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booksDetailsLabel.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        booksDetailsLabel.setForeground(new java.awt.Color(255, 255, 255));
        booksDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booksDetailsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        booksDetailsLabel.setText("Books Details");
        booksDetailsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksDetailsLabelMouseClicked(evt);
            }
        });
        leftPanel.add(booksDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 290, 100));

        HomeBtn.setBackground(new java.awt.Color(255, 0, 51));
        HomeBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        HomeBtn.setText("Home");
        HomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        leftPanel.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 137, 33));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        leftPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 203, 260, 10));

        bookNamelabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        bookNamelabel.setForeground(new java.awt.Color(255, 255, 255));
        bookNamelabel.setText("Name :");
        leftPanel.add(bookNamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        bookIdLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        bookIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookIdLabel.setText("Acc. No :");
        leftPanel.add(bookIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        subjectLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        subjectLabel.setForeground(new java.awt.Color(255, 255, 255));
        subjectLabel.setText("Subject :");
        leftPanel.add(subjectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 90, -1));

        authorLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        authorLabel.setForeground(new java.awt.Color(255, 255, 255));
        authorLabel.setText("Author :");
        leftPanel.add(authorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        issuedToLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        issuedToLabel.setForeground(new java.awt.Color(255, 255, 255));
        issuedToLabel.setText("Issued To  :");
        leftPanel.add(issuedToLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 110, -1));

        setBookIdLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        setBookIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        setBookIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftPanel.add(setBookIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 220, 30));

        setBookNamelabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        setBookNamelabel.setForeground(new java.awt.Color(255, 255, 255));
        setBookNamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftPanel.add(setBookNamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 270, 30));

        setAuthorLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        setAuthorLabel.setForeground(new java.awt.Color(255, 255, 255));
        setAuthorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftPanel.add(setAuthorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 230, 30));

        setIssuedToLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        setIssuedToLabel.setForeground(new java.awt.Color(255, 255, 255));
        setIssuedToLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftPanel.add(setIssuedToLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 240, 30));

        setSubjectLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        setSubjectLabel.setForeground(new java.awt.Color(255, 255, 255));
        setSubjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftPanel.add(setSubjectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 240, 30));

        BooksResultBox.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        BooksResultBox.setForeground(new java.awt.Color(255, 255, 255));
        BooksResultBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftPanel.add(BooksResultBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 370, 30));

        bottomPanel.add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 700));

        RightPanel.setBackground(new java.awt.Color(152, 255, 140));
        RightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        issueBookLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        issueBookLabel.setForeground(new java.awt.Color(255, 255, 255));
        issueBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        issueBookLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        issueBookLabel.setText("Issue Book");
        issueBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueBookLabelMouseClicked(evt);
            }
        });
        RightPanel.add(issueBookLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 270, 110));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        RightPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 260, 10));

        issueStudentIdlabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        issueStudentIdlabel.setForeground(new java.awt.Color(255, 255, 255));
        issueStudentIdlabel.setText("Issue Student Id :");
        RightPanel.add(issueStudentIdlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        setDefaultDateLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        setDefaultDateLabel.setForeground(new java.awt.Color(0, 153, 0));
        RightPanel.add(setDefaultDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 510, 30));

        issueDateLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        issueDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        issueDateLabel.setText("Issue Date :");
        RightPanel.add(issueDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 160, -1));

        resultBoxLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        resultBoxLabel.setForeground(new java.awt.Color(255, 255, 255));
        resultBoxLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightPanel.add(resultBoxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 540, 30));

        ReturnDateLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        ReturnDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        ReturnDateLabel.setText("Return Date :");
        RightPanel.add(ReturnDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 140, -1));

        studentIdEditText.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        studentIdEditText.setPlaceholder("Enter Student Id");
        studentIdEditText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentIdEditTextFocusLost(evt);
            }
        });
        studentIdEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdEditTextActionPerformed(evt);
            }
        });
        RightPanel.add(studentIdEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 300, 40));

        bookIdEditText.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        bookIdEditText.setPlaceholder("Enter Accession  Number");
        bookIdEditText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookIdEditTextFocusLost(evt);
            }
        });
        bookIdEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIdEditTextActionPerformed(evt);
            }
        });
        RightPanel.add(bookIdEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 300, 40));

        issueBookBtn.setBackground(new java.awt.Color(204, 255, 153));
        issueBookBtn.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        issueBookBtn.setForeground(new java.awt.Color(255, 51, 51));
        issueBookBtn.setText("Issue Book");
        issueBookBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        issueBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueBookBtnMouseClicked(evt);
            }
        });
        issueBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookBtnActionPerformed(evt);
            }
        });
        RightPanel.add(issueBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 613, 310, 30));

        issueBookIdLabel1.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        issueBookIdLabel1.setForeground(new java.awt.Color(255, 255, 255));
        issueBookIdLabel1.setText("Issue Acc. No. :");
        RightPanel.add(issueBookIdLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 170, -1));
        RightPanel.add(issueDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 300, -1));
        RightPanel.add(returnDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 300, -1));

        bottomPanel.add(RightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 540, 700));

        centerPanel.setBackground(new java.awt.Color(153, 51, 255));
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        centerPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 290, 10));

        studentDetailsLabel.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        studentDetailsLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentDetailsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Student_Registration_100px_2.png"))); // NOI18N
        studentDetailsLabel.setText("Student's Details");
        studentDetailsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentDetailsLabelMouseClicked(evt);
            }
        });
        centerPanel.add(studentDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 330, -1));

        setIssuedBooksLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        setIssuedBooksLabel.setForeground(new java.awt.Color(255, 255, 255));
        setIssuedBooksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centerPanel.add(setIssuedBooksLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 220, 30));

        setCourseLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        setCourseLabel.setForeground(new java.awt.Color(255, 255, 255));
        setCourseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centerPanel.add(setCourseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 220, 30));

        setStudentNamelabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        setStudentNamelabel.setForeground(new java.awt.Color(255, 255, 255));
        setStudentNamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centerPanel.add(setStudentNamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 220, 30));

        studentStatusLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        studentStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentStatusLabel.setText("Student Status :");
        centerPanel.add(studentStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 160, -1));

        setStudentStatusLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        setStudentStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        setStudentStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centerPanel.add(setStudentStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 220, 30));

        studentIdLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        studentIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentIdLabel.setText("Student Id :");
        centerPanel.add(studentIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        studentNamelabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        studentNamelabel.setForeground(new java.awt.Color(255, 255, 255));
        studentNamelabel.setText("Name :");
        centerPanel.add(studentNamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        booksIssuedLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        booksIssuedLabel.setForeground(new java.awt.Color(255, 255, 255));
        booksIssuedLabel.setText("Books Issued :");
        centerPanel.add(booksIssuedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 140, -1));

        setStudentIdLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        setStudentIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        setStudentIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centerPanel.add(setStudentIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 220, 30));

        courseLabel.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        courseLabel.setForeground(new java.awt.Color(255, 255, 255));
        courseLabel.setText("Course :");
        centerPanel.add(courseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 80, -1));

        studentResultBox.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        studentResultBox.setForeground(new java.awt.Color(255, 255, 255));
        studentResultBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centerPanel.add(studentResultBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 380, 30));

        bottomPanel.add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 400, 700));

        getContentPane().add(bottomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 720));

        setSize(new java.awt.Dimension(1382, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked

        ControlPanel next = new ControlPanel();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void studentIdEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdEditTextActionPerformed

        issueDateChooser.requestFocus();
    }//GEN-LAST:event_studentIdEditTextActionPerformed

    private void bookIdEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIdEditTextActionPerformed

        studentIdEditText.requestFocus();
    }//GEN-LAST:event_bookIdEditTextActionPerformed

    private void issueBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueBookBtnActionPerformed

    private void issueBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBookBtnMouseClicked

        getData();

        try {
            
            // checking if the requested book  is issued to anyone already or not 
            pst = conn.prepareStatement("Select * from `books` where `bookid` = ?;");
            pst.setString(1, bookId);
            rst = pst.executeQuery();
            if (rst.next()) {

                isIssued = rst.getString("issuedToStudId");

            }else{
                    resultBoxLabel.setText(" Book doesn't exist in DataBase.");
                    resultBoxLabel.setForeground(Color.red);
                    Timer timer = new Timer(3000, (ActionEvent arg0) -> {
                    resultBoxLabel.setText("");
                    });
                    timer.setRepeats(false); // Only execute once
                    timer.start();
            }

            if (isIssued.contentEquals("None")) {

                // Issuing book to Student 
                pst = conn.prepareStatement("Insert into `issuedBooks`(`bookId`,`studentId`,`issueDate`,`returnDate`,`defaultDate`) values(?,?,?,?,?) ;");
                pst.setString(1, bookId);
                pst.setString(2, studentId);
                sqlDate = new java.sql.Date(issueDate.getTime());
                pst.setDate(3, sqlDate);
                sqlDate = new java.sql.Date(returnDate.getTime());
                pst.setDate(4, sqlDate);
                AddDaysToDate(returnDate, 7);
                sqlDate = new java.sql.Date(defaultDate.getTime());
                pst.setDate(5, sqlDate);
                pst.executeUpdate();
                setDefaultDateLabel.setText("Default Date : "+String.valueOf(defaultDate));

                // UPDATING FURTURE REQUIRED DATA IN THE BOOKS AND STUDENT TABLE
                pst = conn.prepareStatement("UPDATE `books` SET `issuedToStudId` = ? where `bookId` = ?;");
                pst.setString(1, studentId);
                pst.setString(2, bookId);
                pst.executeUpdate();

                // checking data in student table
                pst = conn.prepareStatement("select * from `students` where `studentId` = ?;");
                pst.setString(1, studentId);
                rst = pst.executeQuery();
                while(rst.next()) {

                    booksIssuedTillNow = rst.getInt("booksIssued");
//                    System.out.println(booksIssuedTillNow);
                    studentStatus = rst.getString("studentStatus");
//                    System.out.println(studentStatus);
                }

//                 setting status and booksissued data in student table                                           // debug.
                pst = conn.prepareStatement("UPDATE `students` SET `booksIssued` = ? , `studentStatus` = ? where `studentId` = ?;");
                // convert booksissuetillnow column to  int data type
                booksIssuedTillNow++;
//                System.out.println("no of books after updating = "+booksIssuedTillNow);
                pst.setInt(1, booksIssuedTillNow);
                if (booksIssuedTillNow > 0) {
                    studentStatus = "ACTIVE";
                }
                pst.setString(2, studentStatus);
                pst.setString(3, studentId);
                pst.executeUpdate();
                
            } else {
                // if book is already allocated to any student 

                // get student id from book table then pass it out to the resultBoxLabel  // debug
                pst = conn.prepareStatement("Select * from `students` where `studentid` = ?;");
                pst.setString(1, isIssued);
                rst = pst.executeQuery();
                while (rst.next()) {
                    resultBoxLabel.setText(" Book is Already Allocated to " + rst.getString("studentName"));
                    resultBoxLabel.setForeground(Color.red);
                    Timer timer = new Timer(3000, (ActionEvent arg0) -> {
                    resultBoxLabel.setText("");
                    });
                    timer.setRepeats(false); // Only execute once
                    timer.start();
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        getBookDetails();
        getStudentDetails();


    }//GEN-LAST:event_issueBookBtnMouseClicked

    private void bookIdEditTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookIdEditTextFocusLost

        getBookDetails();
        
    }//GEN-LAST:event_bookIdEditTextFocusLost

    private void studentIdEditTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIdEditTextFocusLost

        getStudentDetails();
    }//GEN-LAST:event_studentIdEditTextFocusLost

    private void booksDetailsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksDetailsLabelMouseClicked
        // TODO add your handling code here:
        BooksResultBox.setText("");
        setBookIdLabel.setText("");
        setBookNamelabel.setText("");
        setAuthorLabel.setText("");
        setIssuedToLabel.setText("");
        setSubjectLabel.setText("");
    }//GEN-LAST:event_booksDetailsLabelMouseClicked

    private void studentDetailsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentDetailsLabelMouseClicked
        // TODO add your handling code here:
        studentResultBox.setText("");
        setStudentIdLabel.setText("");
        setStudentNamelabel.setText("");
        setCourseLabel.setText("");
        setIssuedBooksLabel.setText("");
        setStudentStatusLabel.setText("");
    }//GEN-LAST:event_studentDetailsLabelMouseClicked

    private void issueBookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBookLabelMouseClicked
        // TODO add your handling code here:
        resultBoxLabel.setText("");
        bookIdEditText.setText("");
        studentIdEditText.setText("");
        setDefaultDateLabel.setText("");
    }//GEN-LAST:event_issueBookLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IssueBooks().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BooksResultBox;
    private javax.swing.JLabel HomeBtn;
    private javax.swing.JLabel ReturnDateLabel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JLabel authorLabel;
    private app.bolivia.swing.JCTextField bookIdEditText;
    private javax.swing.JLabel bookIdLabel;
    private javax.swing.JLabel bookNamelabel;
    private javax.swing.JLabel booksDetailsLabel;
    private javax.swing.JLabel booksIssuedLabel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JButton issueBookBtn;
    private javax.swing.JLabel issueBookIdLabel1;
    private javax.swing.JLabel issueBookLabel;
    private com.toedter.calendar.JDateChooser issueDateChooser;
    private javax.swing.JLabel issueDateLabel;
    private javax.swing.JLabel issueStudentIdlabel;
    private javax.swing.JLabel issuedToLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel resultBoxLabel;
    private com.toedter.calendar.JDateChooser returnDateChooser;
    private javax.swing.JLabel setAuthorLabel;
    private javax.swing.JLabel setBookIdLabel;
    private javax.swing.JLabel setBookNamelabel;
    private javax.swing.JLabel setCourseLabel;
    private javax.swing.JLabel setDefaultDateLabel;
    private javax.swing.JLabel setIssuedBooksLabel;
    private javax.swing.JLabel setIssuedToLabel;
    private javax.swing.JLabel setStudentIdLabel;
    private javax.swing.JLabel setStudentNamelabel;
    private javax.swing.JLabel setStudentStatusLabel;
    private javax.swing.JLabel setSubjectLabel;
    private javax.swing.JLabel studentDetailsLabel;
    private app.bolivia.swing.JCTextField studentIdEditText;
    private javax.swing.JLabel studentIdLabel;
    private javax.swing.JLabel studentNamelabel;
    private javax.swing.JLabel studentResultBox;
    private javax.swing.JLabel studentStatusLabel;
    private javax.swing.JLabel subjectLabel;
    // End of variables declaration//GEN-END:variables
}
