package Jframe;

import Adapters.dbhandler;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author HIMANSHU TYAGI BCA SEM 5 ROLL NO 200954106032.
 */
public class SignUpPage extends javax.swing.JFrame {

    private ResultSet rst;
    private static Connection conn;
    private PreparedStatement pst;
    private String Username,Password, MasterPassword, confirmMasterPassword, isLoggedIn, sql;
   

    public void showmessage(String message) {

        ResultMessageLabel1.setText(message);
        Timer timer = new Timer(3000, (ActionEvent arg0) -> {
            ResultMessageLabel1.setText(" ");
        });
        timer.setRepeats(false); // Only execute once
        timer.start();

    }

    private Boolean getData() {

        Username = usernameEditText.getText();
        Password = String.valueOf(passwordEditText.getPassword());
        MasterPassword = String.valueOf(masterpasswordEditText.getPassword());
        return true;
    }

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        try {
            conn = dbhandler.getDbConnection();
        } catch (SQLException ex) {
            ex.getMessage();
        }
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("resources/SCZ.png")));
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new org.jdesktop.swing.animation.rendering.JRendererPanel();
        leftPanelimage = new rojerusan.RSLabelImage();
        jRendererPanel1 = new org.jdesktop.swing.animation.rendering.JRendererPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rightPanel = new org.jdesktop.swing.animation.rendering.JRendererPanel();
        jLabel4 = new javax.swing.JLabel();
        usernameicon = new rojerusan.RSLabelImage();
        usernameEditText = new app.bolivia.swing.JCTextField();
        passwordIcon = new rojerusan.RSLabelImage();
        jLabel5 = new javax.swing.JLabel();
        signUpBtn = new rojerusan.RSMaterialButtonRectangle();
        loginBtn = new rojerusan.RSMaterialButtonRectangle();
        jLabel6 = new javax.swing.JLabel();
        ResultMessageLabel1 = new javax.swing.JLabel();
        BrandNameContainerLeftandRight = new javax.swing.JPanel();
        brandnameLeft = new javax.swing.JLabel();
        brandnameRight = new javax.swing.JLabel();
        developerName = new javax.swing.JLabel();
        passwordIcon1 = new rojerusan.RSLabelImage();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        masterpasswordEditText = new javax.swing.JPasswordField();
        passwordEditText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("SignupFrame"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        LeftPanel.setPreferredSize(new java.awt.Dimension(990, 700));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanelimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/signup-library-icon.png"))); // NOI18N
        LeftPanel.add(leftPanelimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 640, 590));

        jRendererPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("D.A.V. COLLEGE MUZAFFARNAGAR");
        jRendererPanel1.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIBRARY MANAGEMENT SYSTEM");
        jRendererPanel1.add(jLabel1);

        LeftPanel.add(jRendererPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 470, 80));

        getContentPane().add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 950, 750));

        rightPanel.setBackground(new java.awt.Color(153, 51, 255));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("@Username");
        rightPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 130, -1));

        usernameicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        rightPanel.add(usernameicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 30, 30));

        usernameEditText.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        usernameEditText.setPlaceholder("Enter Username here");
        usernameEditText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameEditTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameEditTextFocusLost(evt);
            }
        });
        usernameEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameEditTextActionPerformed(evt);
            }
        });
        rightPanel.add(usernameEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 260, 40));

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N
        rightPanel.add(passwordIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("@MasterPassword");
        rightPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 130, -1));

        signUpBtn.setBackground(new java.awt.Color(102, 255, 102));
        signUpBtn.setText("SignUp");
        signUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        signUpBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signUpBtnKeyPressed(evt);
            }
        });
        rightPanel.add(signUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, 40));

        loginBtn.setBackground(new java.awt.Color(102, 204, 255));
        loginBtn.setText("Login");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        rightPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, -1, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Master Password will be required to create new User");
        rightPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 390, 30));

        ResultMessageLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        ResultMessageLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ResultMessageLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightPanel.add(ResultMessageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 420, 50));

        BrandNameContainerLeftandRight.setBackground(new java.awt.Color(153, 51, 255));
        BrandNameContainerLeftandRight.setName("BrandNamePanel"); // NOI18N

        brandnameLeft.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        brandnameLeft.setForeground(new java.awt.Color(255, 51, 51));
        brandnameLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brandnameLeft.setText("SuperCruZe");
        BrandNameContainerLeftandRight.add(brandnameLeft);

        brandnameRight.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        brandnameRight.setForeground(new java.awt.Color(255, 255, 255));
        brandnameRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brandnameRight.setText("Technologies");
        BrandNameContainerLeftandRight.add(brandnameRight);

        rightPanel.add(BrandNameContainerLeftandRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 370, 40));

        developerName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        developerName.setForeground(new java.awt.Color(255, 255, 255));
        developerName.setText("Designed and Developed By Himanshu Tyagi");
        rightPanel.add(developerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 390, -1));

        passwordIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N
        rightPanel.add(passwordIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 30, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("@Password");
        rightPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 130, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Control  Panel");
        rightPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 240, 30));

        masterpasswordEditText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                masterpasswordEditTextFocusLost(evt);
            }
        });
        masterpasswordEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterpasswordEditTextActionPerformed(evt);
            }
        });
        rightPanel.add(masterpasswordEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 260, 40));

        passwordEditText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordEditTextFocusLost(evt);
            }
        });
        passwordEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordEditTextActionPerformed(evt);
            }
        });
        rightPanel.add(passwordEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 332, 260, 40));

        getContentPane().add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 450, 750));

        setSize(new java.awt.Dimension(1366, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField1ActionPerformed

    private void jCTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField2ActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        LoginPage next = new LoginPage();
        next.setVisible(true);
        dispose();

    }//GEN-LAST:event_loginBtnActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed

        if (getData()) {
            try {

                sql = "Select * from  masterdata ;";
                pst = conn.prepareStatement(sql);
                rst = pst.executeQuery();
                if (rst.next()) {
                    confirmMasterPassword = rst.getString(1);
                }
//                System.out.println(confirmMasterPassword);
                if ((confirmMasterPassword.equalsIgnoreCase(String.valueOf(MasterPassword)))) {

                    sql = "Select * from `users` where `username` Like '" + Username + "';";
                    pst = conn.prepareStatement(sql);
                    rst = pst.executeQuery();
                    if (rst.next()) {
                        showmessage("User Already Exists...");
                    } else {
                        sql = "INSERT INTO `users` (`username`, `password`)  values(?,?);";
                        pst = conn.prepareStatement(sql);
                        pst.setString(1, Username);
                        pst.setString(2, Password);
                        int updateRowCount = pst.executeUpdate();
                        if (updateRowCount > 0) {
                            // sending user to control panel
                            isLoggedIn = "true";
                            sql = "update `masterdata` set `userLoggedIn` = '" + Username + "' , `isLoggedIn` = '" + isLoggedIn + "';";
                            pst = conn.prepareStatement(sql);
                            pst.executeUpdate();
                            ControlPanel next = new ControlPanel();
                            next.setVisible(true);
                            dispose();
                        } else {

                            showmessage("Oops! User Creation Failure");
                        }
                    } // upper else block
                } else {
                    showmessage("Wrong Master Password!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } // validation block

    }//GEN-LAST:event_signUpBtnActionPerformed

    private void usernameEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameEditTextActionPerformed
        if (String.valueOf(usernameEditText.getText()).isEmpty()) {
            showmessage("Username shouldn't be Empty!");
        } else {

            Pattern namePattern = Pattern.compile("^[a-zA-Z ]{4,16}$");
            Matcher nameMatcher = namePattern.matcher(usernameEditText.getText());
            if (!nameMatcher.matches()) {
                showmessage("Username should not cotain any number! ");
                usernameEditText.requestFocus();
            } else {
                passwordEditText.requestFocus();
            }
        }

    }//GEN-LAST:event_usernameEditTextActionPerformed

    private void signUpBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signUpBtnKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_signUpBtnKeyPressed

    private void usernameEditTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameEditTextFocusGained


    }//GEN-LAST:event_usernameEditTextFocusGained

    private void usernameEditTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameEditTextFocusLost


    }//GEN-LAST:event_usernameEditTextFocusLost

    private void masterpasswordEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterpasswordEditTextActionPerformed
        // TODO add your handling code here:
        if (!String.valueOf(masterpasswordEditText.getPassword()).equals("")) {
            signUpBtn.doClick();
        } else {
            showmessage("MasterPassword shouldn't be Empty!");
        }
    }//GEN-LAST:event_masterpasswordEditTextActionPerformed

    private void passwordEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordEditTextActionPerformed
        if (String.valueOf(passwordEditText.getPassword()).equals("")) {
            showmessage("Password shouldn't be Empty!");
        } else {

            String regex = "^[a-zA-Z0-9_!#$%&amp;'*+/=?`{|}~^-]+(?:\\.[a-zA-Z0-9_!#$%&amp;'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$";
            Pattern w = Pattern.compile(regex);
            Matcher a = w.matcher(String.valueOf(passwordEditText.getPassword()));
            if (!a.matches() ) {
                //JOptionPane.showMessageDialog(null, "Enter a valid email id");
                showmessage("Password must be Alphanumeric and contain @!");
                passwordEditText.requestFocus();
            }else{
            masterpasswordEditText.requestFocus();
            }
        }

    }//GEN-LAST:event_passwordEditTextActionPerformed

    private void passwordEditTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordEditTextFocusLost


    }//GEN-LAST:event_passwordEditTextFocusLost

    private void masterpasswordEditTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_masterpasswordEditTextFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_masterpasswordEditTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BrandNameContainerLeftandRight;
    private org.jdesktop.swing.animation.rendering.JRendererPanel LeftPanel;
    private javax.swing.JLabel ResultMessageLabel1;
    private javax.swing.JLabel brandnameLeft;
    private javax.swing.JLabel brandnameRight;
    private javax.swing.JLabel developerName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private org.jdesktop.swing.animation.rendering.JRendererPanel jRendererPanel1;
    private rojerusan.RSLabelImage leftPanelimage;
    private rojerusan.RSMaterialButtonRectangle loginBtn;
    private javax.swing.JPasswordField masterpasswordEditText;
    private javax.swing.JPasswordField passwordEditText;
    private rojerusan.RSLabelImage passwordIcon;
    private rojerusan.RSLabelImage passwordIcon1;
    private org.jdesktop.swing.animation.rendering.JRendererPanel rightPanel;
    private rojerusan.RSMaterialButtonRectangle signUpBtn;
    private app.bolivia.swing.JCTextField usernameEditText;
    private rojerusan.RSLabelImage usernameicon;
    // End of variables declaration//GEN-END:variables
}
