package Jframe;

import Adapters.dbhandler;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HIMANSHU TYAGI BCA SEM 5 ROLL NO 200954106032.
 */
public class viewRecords extends javax.swing.JFrame {

    String bookId, bookName, studentId, studentName, fatherName, phoneNo, address;
    Date issueDate, returnDate;
    private static ResultSet rst;
    private static Connection conn;
    private static PreparedStatement pst;
    private static String sql;
    java.sql.Date issueSqlDate, returnSqlDate;

    /**
     * Creates new form Defaulters
     */
    public viewRecords() {
        try {
            conn = dbhandler.getDbConnection();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("resources/SCZ.png")));
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

    }

    // setting data into table from database
    private void setDataTable() {

        clearTable();
        try {

            // GETTING DATA FROM STUDENT TABLE
            sql = """
                  SELECT books.bookId,books.bookName,students.studentId,students.studentName,students.fatherName,students.phoneNo,students.address
                  FROM ( ( issuedbooks INNER JOIN books ON issuedbooks.bookId = books.bookId  ) INNER JOIN students ON issuedbooks.studentId = students.studentId
                      ) where `issueDate` >= ? AND `returnDate` <= ? ;""";
            pst = conn.prepareStatement(sql);
            issueDate = issueDateChooser.getDate();
            issueSqlDate = new java.sql.Date(issueDate.getTime());
            pst.setDate(1, issueSqlDate);
            returnDate = returnDateChooser.getDate();
            returnSqlDate = new java.sql.Date(returnDate.getTime());
            pst.setDate(2, returnSqlDate);
            rst = pst.executeQuery();
            while (rst.next()) {
                bookId = rst.getString("bookId");
                bookName = rst.getString("bookName");
                studentId = rst.getString("studentId");
                studentName = rst.getString("studentName");
                fatherName = rst.getString("fatherName");
                phoneNo = rst.getString("phoneNo");
                address = rst.getString("address");

                Object[] obj = {bookId, bookName, studentId, studentName, fatherName, phoneNo, address};
                DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
                model.addRow(obj);

            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void clearTable() {

        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        viewAllDetailsLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        HomeBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        issueDateChooser = new com.toedter.calendar.JDateChooser();
        returnDateChooser = new com.toedter.calendar.JDateChooser();
        lowerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Recordas in a Range");

        upperPanel.setBackground(new java.awt.Color(204, 102, 255));
        upperPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewAllDetailsLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        viewAllDetailsLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewAllDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewAllDetailsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Book_50px_1.png"))); // NOI18N
        viewAllDetailsLabel.setText("View All Record In Range");
        viewAllDetailsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllDetailsLabelMouseClicked(evt);
            }
        });
        upperPanel.add(viewAllDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 510, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        upperPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 400, 20));

        HomeBtn.setBackground(new java.awt.Color(255, 0, 51));
        HomeBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        HomeBtn.setText("Home");
        HomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        upperPanel.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 137, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Issue Date :");
        upperPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Return Date :");
        upperPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        searchBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        searchBtn.setText("Search Data");
        searchBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });
        upperPanel.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, 160, -1));
        upperPanel.add(issueDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, -1));
        upperPanel.add(returnDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 230, -1));

        lowerPanel.setBackground(new java.awt.Color(255, 255, 255));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "Student's Id", "Student's Name", "Father's Name", "Phone No.", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setColorBackgoundHead(new java.awt.Color(204, 102, 255));
        dataTable.setColorBordeHead(new java.awt.Color(255, 255, 255));
        dataTable.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        dataTable.setColorFilasForeground2(new java.awt.Color(204, 102, 255));
        dataTable.setColorSelBackgound(new java.awt.Color(204, 204, 204));
        dataTable.setFuenteFilas(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dataTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dataTable.setFuenteHead(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dataTable.setRowHeight(30);
        jScrollPane1.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            dataTable.getColumnModel().getColumn(2).setPreferredWidth(15);
            dataTable.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        javax.swing.GroupLayout lowerPanelLayout = new javax.swing.GroupLayout(lowerPanel);
        lowerPanel.setLayout(lowerPanelLayout);
        lowerPanelLayout.setHorizontalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        lowerPanelLayout.setVerticalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked

        ControlPanel next = new ControlPanel();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void viewAllDetailsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllDetailsLabelMouseClicked

        setDataTable();
    }//GEN-LAST:event_viewAllDetailsLabelMouseClicked

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked

        setDataTable();
    }//GEN-LAST:event_searchBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewRecords().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeBtn;
    private rojeru_san.complementos.RSTableMetro dataTable;
    private com.toedter.calendar.JDateChooser issueDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel lowerPanel;
    private com.toedter.calendar.JDateChooser returnDateChooser;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel upperPanel;
    private javax.swing.JLabel viewAllDetailsLabel;
    // End of variables declaration//GEN-END:variables
}
